In [21]:
import numpy as np
import sys
np.set_printoptions(precision=10, linewidth=200, suppress=True)
import psi4
from helper_PFCI import PFHamiltonianGenerator
from helper_PFCI import Determinant
from helper_cqed_rhf import cqed_rhf
np.set_printoptions(threshold=sys.maxsize)
psi4.core.set_output_file('output.dat', False)
import os
import json

In [22]:
# options for mgf
mol_str = """
Li
H 1 1.5
symmetry c1
"""

options_dict = {
    "basis": "6-31G",
    "scf_type": "pk",
    "e_convergence": 1e-10,
    "d_convergence": 1e-10,
    "save_jk" : True
}


psi4.set_options(options_dict)
mol = psi4.geometry(mol_str)


In [23]:
mol_tmpl = """
Li
H 1 **R**
symmetry c1
"""

mol_str = """
Li
H 1 1.5
symmetry c1
"""

N_R = 200
# N_el = 50
# all_states = np.linspace(0, N_el-1, N_el, dtype=int)
r_array = np.linspace(1.4, 2.2, N_R)

# E_array = np.zeros((N_R, N_el))
# Mu_array = np.zeros((N_R, N_el, N_el, 3))
# psi4.set_options(options_dict)

# r_idx = 0
# for r in r_array:
#     mol_str = mol_tmpl.replace("**R**", str(r))
#     print(mol_str)
#     mol = psi4.geometry(mol_str)
#     #scf_e, wfn = psi4.energy('SCF', return_wfn=True)
#     #fci_energy = psi4.energy('fci',ref_wfn=wfn)
    
#     LiH = PFHamiltonianGenerator(mol_str, options_dict, cavity_free_dict)
#     #assert np.isclose(fci_energy, LiH.CIeigs[0], 1e-7)
#     # sort out states with dipole-allowed transition from ground state
#     singlet_states = LiH.sort_dipole_allowed_states( N_el)
#     print(singlet_states)
    
#     E_array[r_idx, :] = LiH.CIeigs[singlet_states]
#     Mu_array[r_idx, :, :, :] = LiH.compute_dipole_moments(singlet_states)
    
#     # uncomment to try not sorting singlet states
#     #E_array[r_idx, :] = LiH.CIeigs[all_states]
#     #Mu_array[r_idx, :, :, :] = LiH.compute_dipole_moments(all_states)
    
#     r_idx += 1



In [24]:
from matplotlib import pyplot as plt
somedir=os.getcwd()
print(somedir)

/Users/rmandern/code/SCQED-PCQED/Formaldehyde


In [25]:
# np.save("LiH_631G_FCI_E_array", E_array)
# np.save("LiH_631G_Mu_array", Mu_array)

In [26]:
print(os.path.abspath("."))

#E_array = np.load(LiH_631G_FCI_E_Array.npy)
E_array_F = np.load('E_formaldehyde_rCO_1p30_cas_88_dipole_allowed_transitions.npy')
Mu_array_F = np.load('Mu_formaldehyde_rCO_1p30_cas_88_dipole_allowed_transitions.npy')
# r_array = np.load('LiH_r_array.npy')

/Users/rmandern/code/SCQED-PCQED/Formaldehyde


In [44]:
# print(E_array_F.shape)
print(Mu_array_F.shape)
print(lambdas)
lam_np1 = [0.0, 0.0, 0.005]
print(lam_np.shape)
d_ag = np.matmul(Mu_array_F, lam_np1)
# print(d_ag)

(200, 200, 3)
[[0.0, 0.0, 0.0], [0.0, 0.0, 0.005], [0.0, 0.0, 0.01], [0.0, 0.0, 0.015], [0.0, 0.0, 0.02], [0.0, 0.0, 0.025], [0.0, 0.0, 0.03], [0.0, 0.0, 0.035], [0.0, 0.0, 0.04], [0.0, 0.0, 0.045], [0.0, 0.0, 0.05]]
(11, 3)


In [43]:
# open json file
f = open("CH2O_CO_r_1.3_casci_cc-pVDZ_n_act_els_8_n_act_orbs_8_dipole_allowed.json")
data = json.load(f)


FileNotFoundError: [Errno 2] No such file or directory: 'CH2O_CO_r_1.3_casci_cc-pVDZ_n_act_els_8_n_act_orbs_8_dipole_allowed.json'

In [30]:
# get the array of lambda values from the json file
lambdas = data["model"]["lambda_vector"]
print(lambdas)
lam_np = np.array(lambdas)
print(lam_np)

[[0.0, 0.0, 0.0], [0.0, 0.0, 0.005], [0.0, 0.0, 0.01], [0.0, 0.0, 0.015], [0.0, 0.0, 0.02], [0.0, 0.0, 0.025], [0.0, 0.0, 0.03], [0.0, 0.0, 0.035], [0.0, 0.0, 0.04], [0.0, 0.0, 0.045], [0.0, 0.0, 0.05]]
[[0.    0.    0.   ]
 [0.    0.    0.005]
 [0.    0.    0.01 ]
 [0.    0.    0.015]
 [0.    0.    0.02 ]
 [0.    0.    0.025]
 [0.    0.    0.03 ]
 [0.    0.    0.035]
 [0.    0.    0.04 ]
 [0.    0.    0.045]
 [0.    0.    0.05 ]]


In [ ]:
# get the omega value from the json file
omega_cav = data["model"]["omega"]

In [ ]:
# determine how many lambda values will be in the scan
N_l = len(lambdas)
print(N_l)

\begin{equation}
\hat{H}_{\alpha n, \beta m} = \left( E_{\alpha}(R) + n \omega \right) \delta_{\alpha \beta} \delta_{nm} + \sqrt{\frac{\omega}{2}} \lambda \cdot \mu_{\alpha \beta}(R) \left(\sqrt{n} \delta_{n,m-1} + \sqrt{n+1} \delta_{n,m+1} \right)  \\
+\frac{1}{2} \sum_{\gamma = 1}^N \lambda \cdot \mu_{\alpha, \gamma}(R) \lambda \cdot \mu_{\gamma, \beta} \delta_{nm}
\end{equation}


In [ ]:
def build_pf_hamiltonian(n_el, n_ph, E_R, omega, lamvec, mu):
    """
    Given an array of n_el E_R values and an n_ph states with fundamental energy omega
    build the PF Hamiltonian
    
    n_el : int
        the number of electronic states (n_el = 1 means only ground-state)
    
    n_ph : int
        the number of photon occupation states (n_ph = 1 means only the |0> state)
    
    E_R : np.array of floats
        the electronic energies
        
    omega : float
        the energy of the photonic mode
        
    lamvec : np.array of floats
        the lambda vector
        
    mu : (n_el x n_el x 3) np.array of floats 
        mu[i, j, k] is the kth cartesian component of the dipole moment expectation value between 
        state i and state j
    
    """
    H_PF = np.zeros((n_el * n_ph, n_el * n_ph))
    
    # take care of the diagonals first
    # bare electronic and photonic energy
    for n in range(n_ph):
        for a in range(n_el):
            na = n * n_el + a
            H_PF[na,na] = E_R[a] + n * omega
        
    # diagonal dipole self energy
    for n in range(n_ph):
        for a in range(n_el):
            na = n * n_el + a
            for g in range(n_el):
                H_PF[na,na] += 0.5 * np.dot(lamvec, mu[a,g,:]) * np.dot(lamvec, mu[g,a,:])
            
    # off-diagonal dipole self energy
    for n in range(n_ph):
        for a in range(n_el):
            na = n * n_el + a
            for b in range(n_el):
                nb = n * n_el + b
                for g in range(n_el):
                    if a != b:
                        H_PF[na, nb] += 0.5 * np.dot(lamvec, mu[a,g,:]) * np.dot(lamvec, mu[g, b, :])
                
    # off-diagonal bilinear coupling
    for n in range(n_ph):
        for a in range(n_el):
            na = n * n_el + a
            
            for m in range(n_ph):
                for b in range(n_el):
                    mb = m * n_el + b
                    
                    if n == (m-1) and a != b:
                        #print(n, a, na, m, b, mb)
                        H_PF[na,mb] = -np.sqrt(omega / 2) * np.dot(lamvec, mu[a,b,:]) * np.sqrt(m) 
                        H_PF[mb, na] = -np.sqrt(omega / 2) * np.dot(lamvec, mu[a,b,:]) * np.sqrt(m) 
                        
                    elif n == (m+1) and a != b:
                        #print(n, a, na, m, b, mb)
                        H_PF[na, mb] = -np.sqrt(omega / 2) * np.dot(lamvec, mu[a,b,:]) * np.sqrt(m+1) 
                        H_PF[mb, na] = -np.sqrt(omega / 2) * np.dot(lamvec, mu[a,b,:]) * np.sqrt(m+1)
                        
    
    return H_PF

\begin{equation}
\hat{H}_{\alpha n, \beta m} = \left( E_{\alpha}(R) + n \omega \right) \delta_{\alpha \beta} \delta_{nm} + \sqrt{\frac{\omega}{2}} \lambda \cdot \mu_{\alpha \beta}(R) \left(\sqrt{n} \delta_{n,m-1} + \sqrt{n+1} \delta_{n,m+1} \right)  \\
+\frac{1}{2} \sum_{\gamma = 1}^N \lambda \cdot \mu_{\alpha, \gamma}(R) \lambda \cdot \mu_{\gamma, \beta} \delta_{nm}
\end{equation}


In [ ]:
np.set_printoptions(precision=6, linewidth=200, suppress=True)
omega_cav = 0.3582 
# lambda_vector = np.array([0.0, 0.0, 0.005])

We want to investigate the mean absolute error of a given polariton potential energy surface as a 
function of electronic and photonic truncation:

$$ {\rm MAE} = \frac{1}{N_R} \sum_i^{N_R} \left| E(R_i) - E^{'}(R_i) \right| $$

where $E^{'}(R_i)$ is a value of the polaritonic PES for a truncated level of theory and $E(R_i)$ is the exact value.

In [ ]:
# def MAE(E, Ep):
#     """
#     function to return the mean absolute error of the approximate PES stored in Ep relative to 
#     the exact PES stored in E
#     """
#     # get length
#     _NR = len(E)
    
#     # take element-by-element difference
#     _diff = E - Ep
    
#     # compute absolute value of differences
#     _absdiff = np.abs(_diff)
    
#     # return sum divided by _NR
#     return np.sum(_absdiff) / _NR

    

In [ ]:
# set the electronic and photonic basis
N_el = 2
N_ph = 2

# create an array of zeros to store the PCQED eigenvalues for each value of lambda
_pcqed_22 = np.zeros((N_l, N_el * N_ph))
# loop over values of lambda, build Hamiltonian, capture eigenvalues
ctr = 0
for lam in lambdas:
    _HPF = build_pf_hamiltonian(N_el, N_ph, E_array_F, omega_cav, lam, Mu_array_F)
    pf_e, pf_c = np.linalg.eigh(_HPF)
    _pcqed_22[ctr, :] = pf_e
    ctr += 1


In [ ]:
print(np.shape(lambdas))
print(np.shape(_pcqed_22))
print(lambdas)
print(_pcqed_22)

In [ ]:
lam_np = np.array(lambdas)
print(np.shape(lambdas))
# plt.plot(lam_np[:,2], _pcqed_22[:,0], label="ground-state")
# plt.plot(lam_np[:,2],_pcqed_22[:,1], label='first_excited_state')
# plt.plot(lam_np[:,2],_pcqed_22[:,2], label='second_excited_state')
plt.plot(lam_np[:,2],_pcqed_22[:,3], label='Third_excited_state')
# plt.plot(lambdas[:,2],_pcqed_22[:,4], label='fourth_excited_state')
# plt.ylim(-0.0002, -0.0007)
# plt.ylim(-113.556, -113.50)
# plt.grid()
plt.legend()

In [ ]:

N_el = 4
N_ph = 2

# create an array of zeros to store the PCQED eigenvalues for each value of lambda
_pcqed_42 = np.zeros((N_l, N_el * N_ph))
# loop over values of lambda, build Hamiltonian, capture eigenvalues
ctr = 0
for lam in lambdas:
    _HPF = build_pf_hamiltonian(N_el, N_ph, E_array_F, omega_cav, lam, Mu_array_F)
    pf_e, pf_c = np.linalg.eigh(_HPF)
    _pcqed_42[ctr, :] = pf_e
    ctr += 1


In [ ]:
# plt.plot(lam_np[:,2], _pcqed_42[:,0], label="ground-state")
plt.plot(lam_np[:,2],_pcqed_42[:,1], label='first_excited_state')
plt.plot(lam_np[:,2],_pcqed_42[:,2], label='second_excited_state')
plt.plot(lam_np[:,2],_pcqed_42[:,3], label='Third_excited_state')
plt.plot(lam_np[:,2],_pcqed_42[:,4], label='fourth_excited_state')
plt.xlabel('lambda')
plt.ylabel('Energy')
# plt.ylim(-0.0002, -0.0007)
# plt.ylim(-113.556, -113.50)
# plt.grid()
plt.legend()


In [ ]:
N_el = 50
N_ph = 5

# create an array of zeros to store the PCQED eigenvalues for each value of lambda
_pcqed_505 = np.zeros((N_l, N_el * N_ph))
# loop over values of lambda, build Hamiltonian, capture eigenvalues
ctr = 0
for lam in lambdas:
    _HPF = build_pf_hamiltonian(N_el, N_ph, E_array_F, omega_cav, lam, Mu_array_F)
    pf_e, pf_c = np.linalg.eigh(_HPF)
    _pcqed_505[ctr, :] = pf_e
    ctr += 1

In [ ]:
# plt.plot(lam_np[:,2], _pcqed_42[:,0], label="ground-state")
plt.plot(lam_np[:,2],_pcqed_505[:,1], label='first_excited_state')
plt.plot(lam_np[:,2],_pcqed_505[:,2], label='second_excited_state')
plt.plot(lam_np[:,2],_pcqed_505[:,3], label='Third_excited_state')
plt.plot(lam_np[:,2],_pcqed_505[:,4], label='fourth_excited_state')
plt.xlabel('lambda')
plt.ylabel('Energy')
# plt.ylim(-0.0002, -0.0007)
# plt.ylim(-113.556, -113.50)
# plt.grid()
plt.legend()

In [ ]:
# data_42 = data
# #print(data_52["return_result"])
# data_42["model"]["number_of_electronic_states"] = 4
# data_42["model"]["number_of_photonic_states"] = 2

# # loop over the different lambda values
# energies = []
# for i in range(len(_pcqed_42[:,0])):
#     sub_energies = []
#     for j in range(len(_pcqed_42[0,:])):
#         sub_energies.append(_pcqed_42[i,j])
#     energies.append(sub_energies)

# print(energies)

# data_42["return_result"] = energies

# file_name = "CH2O_CO_r_1.3_pcqed_42.json"
# json_object = json.dumps(data_42, indent=4)
# with open(file_name, "w") as outfile:
#     outfile.write(json_object)

In [ ]:
#comment

In [ ]:
N_el = 50
N_ph = 10

# create an array of zeros to store the PCQED eigenvalues for each value of lambda
_pcqed_5010 = np.zeros((N_l, N_el * N_ph))
# loop over values of lambda, build Hamiltonian, capture eigenvalues
ctr = 0
for lam in lambdas:
    _HPF = build_pf_hamiltonian(N_el, N_ph, E_array_F, omega_cav, lam, Mu_array_F)
    pf_e, pf_c = np.linalg.eigh(_HPF)
    _pcqed_5010[ctr, :] = pf_e
    ctr += 1


In [ ]:
# plt.plot(lam_np[:,2], _pcqed_72[:,0], label="ground-state")
plt.plot(lam_np[:,2],_pcqed_5010[:,1], label='first_excited_state')
plt.plot(lam_np[:,2],_pcqed_5010[:,2], label='second_excited_state')
plt.plot(lam_np[:,2],_pcqed_5010[:,3], label='Third_excited_state')
plt.plot(lam_np[:,2],_pcqed_5010[:,4], label='fourth_excited_state')
# plt.plot(lambdas[:,2],_pcqed_72[:,5], label='fifth_excited_state')
plt.xlabel('lambda')
plt.ylabel('Energy')
# plt.ylim(-0.0002, -0.0007)
# plt.ylim(-113.556, -113.50)
# plt.grid()
plt.legend()

In [ ]:
plt.plot(lam_np[:,2],_pcqed_5010[:,0],'ro-', label='g_state_5010')
# plt.plot(lam_np[:,2],_pcqed_5010[:,2], label='second_excited_state')
plt.plot(lam_np[:,2],_pcqed_505[:,0],'bo', label='g_state_505')
plt.xlabel('lambda')
plt.ylabel('Energy')
# plt.ylim(-0.0002, -0.0007)
# plt.ylim(-113.556, -113.50)
# plt.grid()
plt.legend()
print(_pcqed_5010[:,0])
print(_pcqed_505[:,0])

In [ ]:
# # data_5010 = data
# #print(data_52["return_result"])
# data_5010["model"]["number_of_electronic_states"] = 50
# data_5010["model"]["number_of_photonic_states"] = 10

# # loop over the different lambda values
# energies = []
# for i in range(len(_pcqed_5010[:,0])):
#     sub_energies = []
#     for j in range(len(_pcqed_5010[0,:])):
#         sub_energies.append(_pcqed_5010[i,j])
#     energies.append(sub_energies)

# print(energies)

# data_5010["return_result"] = energies

# file_name = "CH2O_CO_r_1.3_pcqed_5010.json"
# json_object = json.dumps(data_5010, indent=4)
# with open(file_name, "w") as outfile:
#     outfile.write(json_object)

In [ ]:
N_el = 200
N_ph = 5

# create an array of zeros to store the PCQED eigenvalues for each value of lambda
_pcqed_2005 = np.zeros((N_l, N_el * N_ph))
# loop over values of lambda, build Hamiltonian, capture eigenvalues
ctr = 0
for lam in lambdas:
    _HPF = build_pf_hamiltonian(N_el, N_ph, E_array_F, omega_cav, lam, Mu_array_F)
    pf_e, pf_c = np.linalg.eigh(_HPF)
    _pcqed_2005[ctr, :] = pf_e
    ctr += 1


In [ ]:
# plt.plot(lam_np[:,2], _pcqed_72[:,0], label="ground-state")
plt.plot(lam_np[:,2],_pcqed_2005[:,0], label='g_excited_state_2005')
# plt.plot(lam_np[:,2],_pcqed_2005[:,1], label='first_excited_state')
# plt.plot(lam_np[:,2],_pcqed_2005[:,2], label='second_excited_state')
# plt.plot(lam_np[:,2],_pcqed_2005[:,3], label='third_excited_state')
# plt.plot(lam_np[:,2],_pcqed_2005[:,4], label='fourth_excited_state')
# plt.plot(lam_np[:,2],_pcqed_2005[:,5], label='fourth_excited_state')
plt.plot(lam_np[:,2],_pcqed_505[:,0],'ro-', label='g_state_505')
plt.plot(lam_np[:,2],_pcqed_42[:,0],'b', label='g_state_42')
plt.plot(lam_np[:,2],_pcqed_5010[:,0],'y', label='g_state_5010')

plt.xlabel('lambda')
plt.ylabel('Energy')
# plt.ylim(-0.0002, -0.0007)
# plt.ylim(-113.556, -113.50)
# plt.grid()
plt.legend()

In [ ]:
data_2005 = data
print(data_2005["return_result"])
data_2005["model"]["number_of_electronic_states"] = 200
data_2005["model"]["number_of_photonic_states"] = 5

# loop over the different lambda values
energies = []
for i in range(len(_pcqed_2005[:,0])):
    sub_energies = []
    for j in range(len(_pcqed_2005[0,:])):
        sub_energies.append(_pcqed_2005[i,j])
    energies.append(sub_energies)

print(energies)

data_2005["return_result"] = energies

file_name = "CH2O_CO_r_1.3_pcqed_2005.json"
json_object = json.dumps(data_2005, indent=4)
with open(file_name, "w") as outfile:
    outfile.write(json_object)

In [ ]:

#plt.plot(r_array, Eg_QED_FCI_Np_1)
# plt.plot(r_array, E_array[:,0],'bo',  label="No cavity")
# plt.plot(r_array, pf_array_3_2[:,0],'y^' ,label="PCQED_nel3_np2_E0")
# plt.plot(r_array, pf_array_10_5[:,0],'bs' , ms=8,mfc='none',label="PCQED_nel10_np5_E0")
# plt.plot(r_array, pf_array_30_2[:,0],'md' , ms=7,mfc='none',label="PCQED_nel30_np2_E0")
plt.plot(r_array, pf_array_30_30[:,0],label="PCQED_nel30_np30_E0")
plt.plot(r_array, pf_array_50_10[:,0],label="PCQED_nel50_np10_E0")
plt.plot(r_array, pf_array_50_20[:,0],label="PCQED_005_nel30_np20_E0")
# plt.plot(r_array, pf_array[:,1],label="LP")
# plt.plot(r_array, E_array[:,0]+omega_cav, label="E0 + omega")
# plt.plot(r_array, E_array[:,1], label="E1")
# plt.plot(r_array, pf_array[:,2],'ro', label="UP")
# plt.plot(r_array, pf_array[:,3],'bo', label="UP+1")
# plt.plot(r_array, pf_array[:,4],'yo', label="UP+2")
# plt.plot(QEDCI_001_np1_s0[:,0], QEDCI_001_np1_s0[:,1],'rv' , ms=7,mfc='none', label="QEDCI_001_np1_s0")
# plt.plot(QEDCI_001_np5_s0[:,0], QEDCI_001_np5_s0[:,1],'ms' , ms=7,mfc='none', label="QEDCI_001_np5_s0")
# plt.plot(QEDCI_001_np10_s0[:,0], QEDCI_001_np10_s0[:,1],linestyle="dashdot" ,label="QEDCI_001_np10_s0")
# plt.plot(QEDCI_005_np1_s0[:,0], QEDCI_005_np1_s0[:,1],'ro',ms = 6, mfc = 'none', label="QEDCI_005_np1_s0")
# plt.plot(QEDCI_005_np5_s0[:,0], QEDCI_005_np5_s0[:,1],'bo',ms=3,mfc ='none', label="QEDCI_005_np5_s0")
# plt.plot(QEDCI_005_np10_s0[:,0], QEDCI_005_np10_s0[:,1],'ys' , ms=7,mfc='none', label="QEDCI_005_np10_s0")
# plt.plot(QEDCI_001_np1_s1[:,0], QEDCI_001_np1_s1[:,1], label="QEDCI_001_s1",color='black',linestyle='dotted')
# plt.plot(QEDCI_001_np1_s1[:,0], QEDCI_001_np1_s2[:,1], label="QEDCI_001_s2",color='pink',linestyle='dotted')
# plt.xlim(1.4, 2.0)
# plt.ylim(-8.000, -7.980)
# plt.ylim(-8.000, -7.9875)
#lt.title("nel_3__np_40")
#plt.plot(r_array, pf_array[:,4])
plt.legend()
# plt.savefig("LiH_0.05_comparsion.png")


In [ ]:
#plt.plot(r_array, PF_2020[:,0], 'black', label="LP - 20-20")
#plt.plot(r_array, PF_WTRIP[:,0], 'ro', label="LP - 2-2")
plt.plot(r_array, PF_2020[:,1], 'r--', label="LP - 20-2")
plt.plot(r_array, PF_WTRIP[:,2], 'purple', label="UP - 20-20")
plt.plot(r_array, PF_2020[:,2], 'b--', label="UP - 20-2")
plt.plot(r_array, PF_WTRIP[:,3], 'bo', label="UP - 2-2")
plt.legend()
plt.show()
